config/routes.rb
Liveshows::Application.routes.draw do
  resources :bookings

  resources :clubs

  resources :bands

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates_presence_of :name, :num_members
  validates_numericality_of :num_members, :greater_than => 0

  has_many :bookings
  has_many :clubs, :through => :bookings

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  validates_presence_of :band_id, :club_id, :fee, :date
  validates_numericality_of :fee, :greater_than_or_equal_to => 0

  belongs_to :club
  belongs_to :band

  accepts_nested_attributes_for :club
  accepts_nested_attributes_for :band

end

app/models/club.rb
class Club < ActiveRecord::Base
  validates_presence_of :name, :street_address

  has_many :bookings
  has_many :bands, :through => :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show

  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render action: 'show', status: :created, location: @band }
      else
        format.html { render action: 'new' }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :num_members)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @booking }
      else
        format.html { render action: 'new' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:band_id, :club_id, :fee, :date)
    end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :street_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :num_members %><br>
    <%= f.number_field :num_members %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Listing bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Num members</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= band.num_members %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Num members:</strong>
  <%= @band.num_members %>
</p>

<p>

  <h2>Upcoming Shows:</h2>
    <% @band.bookings.each do |c| %>
      <% c.band.bookings %>
    <p><%= "Club Name: #{c.club.name}"%></p>
    <p><%= "Address: #{c.club.street_address}"%></p>
    <p><%= "Date: #{c.date}" %></p>
    <p><%= "Fee:  #{c.fee}" %></p>
    <br>
<% end %>

</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :band_id %><br>
    <%= f.collection_select :band_id, Band.all, :id, :name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :club_id %><br>
    <%= f.collection_select :club_id, Club.all, :id, :name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <thead>
    <tr>
      <th>Band</th>
      <th>Club</th>
      <th>Fee</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.band_id %></td>
        <td><%= booking.club_id %></td>
        <td><%= booking.fee %></td>
        <td><%= booking.date %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Band:</strong>
  <%= @booking.band_id %>
</p>

<p>
  <strong>Club:</strong>
  <%= @booking.club_id %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @booking.fee %>
</p>

<p>
  <strong>Date:</strong>
  <%= @booking.date %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.street_address %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @club.street_address %>
</p>

<p>

<h2>Upcoming Shows:</h2>
<% @club.bookings.each do |c| %>
    <% c.club.bookings %>
    <p><%= "Band Name: #{c.band.name}"%></p>
    <p><%= "Date: #{c.date}" %></p>
    <% days = c.date - Date.today%>
    <% days_r = days.to_i%>
    <p><%= "Days Remaining: #{days_r}" %> </p>
    <br>
<% end %>

</p>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liveshows</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
<hr/>

<h3> Navigation</h3>

<%= link_to "Bands", bands_path %>
<%= link_to "Clubs", clubs_path %>
<%= link_to "Bookings", bookings_path %>


</html>